### ISSUE TITLE
Huge hashrate spike in hashrate report on mining start

### ISSUE THREAD

**Issue by vird** [polyminer1/rhminer#1]
Send  18:49:42   Nonce 791B1E8E found on CPU at 18:49:42. Submitting to pasc.f2pool.com:15555
    Net   18:49:43   Share accepted by pasc.f2pool.com:15555
    Miner 18:49:47   Shares: Accepted 1  Rejected 0  Failed 0 Up for 00:00:09
    Miner 18:49:47   Total: CPU 40960 H/S. AVG 40960.00
    Miner 18:49:57   Shares: Accepted 1  Rejected 0  Failed 0 Up for 00:00:19
    Miner 18:49:57   Total: CPU 307 H/S. AVG 20633.50
    Send  18:50:03   Nonce 3A23FAA4 found on CPU at 18:50:03. Submitting to pasc.f2pool.com:15555
    Send  18:50:04   Nonce 8E4E42D4 found on CPU at 18:50:04. Submitting to pasc.f2pool.com:15555
    Net   18:50:05   Share accepted by pasc.f2pool.com:15555
    Net   18:50:05   Share accepted by pasc.f2pool.com:15555
    Miner 18:50 :07   Shares: Accepted 3  Rejected 0  Failed 0 Up for 00:00:29
    Miner 18:50:07   Total: CPU 410 H/S. AVG 13892.33
    Net   18:50:16   Received new Work FrVtLVcmJS. Work target 0x000f4230 (diff 0.000001)
    Miner 18:50:17   Shares: Accepted 3  Rejected 0  Failed 0 Up for 00:00:39
    Miner 18:50:17   Total: CPU 819 H/S. AVG 10624.00
    Send  18:50:18   Nonce 4B0C362B found on CPU at 18:50:18. Submitting to pasc.f2pool.com:15555
    Net   18:50:19   Share accepted by pasc.f2pool.com:15555

**Comment by polyminer1** [comment]
fixed in the upcoming version.
tnx
