### ISSUE TITLE
Since V2 it is incompatible with the commandline from v1

### ISSUE THREAD

**Issue by OinkOinki** [polyminer1/rhminer#11]

**Comment by OinkOinki** [comment]
verbose network log:
Net   10:10:40   recv : {"id":1,"result":[[["mining.set_difficulty","deadbeefcafebabe2b21000000000000"],["mining.notify","deadbeefcafebabe2b21000000000000"]],"4f70656e706f6f6c2f3834303231393431353030303030303030",8],"error":null}
Net   10:10:40   recv : {"id":null,"method":"mining.set_difficulty","params":[0.000007]}
Net   10:10:40   recv : {"id":null,"method":"mining.notify","params":["5c2","0000000000000000000000000000000000000000000000000000000000000000","7CF50500CA022000B64DCC2FC0F4C2DF73645DE02A1BD0BDB515C65CFDA0DC48955A59DC2A92D8DE20000D5CF076A43878EA0DCD522473CA2B3BBDA495B9118DD942193E54DF75A9015D20A1070000000000050005009DC0E722","C03E05823ADB719F85F81E72A18681ED0D5A0D361FDAF2ADA621FA0F0DA6EAB8E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B85500000000000000000000000016B05B2CB0D18DE41FF82ACA7BE43AFCC43949A81930CE4CE7274EA3",[],"00000000","10000000","5e296306",false]}
Net   10:10:40   Network Error Incorrect coinbase/wallet data.

**Comment by polyminer1** [comment]
Can you provide examples ?

**Comment by OinkOinki** [comment]
I found out that the repository code is not updated. So this is the reason why it does not run.

**Comment by imrecsoka** [comment]
I dont even understand the question here.
Anyways, it was a good read.

**Comment by OinkOinki** [comment]
It is ok. You have enclosed the code. I have built the old one but was expecting the current source. This is not the case, this was the reason why it is no longer working. Better you remove the source code.

**Comment by imrecsoka** [comment]
Okay.

**Comment by polyminer1** [comment]
Code is not released yet.
