### ISSUE TITLE
-devfee option not working

### ISSUE THREAD

**Issue by KL0nLutiy** [polyminer1/rhminer#2]
Miner cannot recognize -devfee option
It says: Invalid command line option '-devfee'

**Comment by polyminer1** [comment]
-devfee is available if you compile the source.

**Comment by SushiTee** [comment]
The command got (accidentally) removed with Version 1.3

https://github.com/polyminer1/rhminer/commit/d67df73d198d5073ad2eb03e2d33865b03e37df3#diff-bda35eb26fce782aca48101b4fda859cL100
