### ISSUE TITLE
more Failed hashes due to duplicate in v1.4

### ISSUE THREAD

**Issue by hashbullet** [polyminer1/rhminer#6]
Started using rhminer v1.4 and found a lot of failed hashes due to duplicate.
The amount of failed hash is related to the mining speed (resources). Currently a cpu only mining (i5 8400 - 6 cputhreads) reported 13 failed in ~30mins. a CPU + GPU mining reported more failed hashes.
The duplicate submission typically happen 2-3 submission after the actual (first accepted) submission.
where as in rhminer v1.3 din't report a single failed hash over multiple weeks on the same hardware.

the same behavior noticed both in CPU only and Volta versions (the only two I tried).

**Comment by polyminer1** [comment]
Can you confirmthat without mining on GPU.
A thing to know for GPU mining of RandomHash is the kernel has a very long execution time.
While the CPU is up to 4x faster, the GPU bound duplicates will tend to half of that on average. That is inherent to RandomHash, and not rhminer. The algorithm is 100% random, there is very little ways to mitigate that.

**Comment by hashbullet** [comment]
Yes. I created the issue after confirming the error with CPU only mining.

**Comment by polyminer1** [comment]
I've been testing on 3 different cpu for 3 days and have literally zero rejected on all my PC.
I suggest you contact your pool in that regard.

**Comment by hashbullet** [comment]
![image](https://user-images.githubusercontent.com/48454156/54456177-cdb17300-475d-11e9-9b49-81430f62edae.png)
It appeared again today. now on C3pool (previously it was Pascalpool).

**Comment by polyminer1** [comment]
Failed shares are not like rejected shares. Failed shares are locally duplicates. Meaning, you have many cores and 2 of them found a valid nonce within the same work package.
RHhminer wont submit them because then the pool will reject them for their are duplicates !
This is inherent to the nature of RandomHash cuz and there is there is no way to make this number go lower. In V1.4, I managed to reduce this from 1.2% to 0.7% on average, but that is it.

**Comment by hashbullet** [comment]
Ok. in that case I will live with this..
as I indicated before, I was never experienced a failed share in v1.3. so was not sure whether it is a bug or random.!
